import './globals.css'
import { TodosProvider } from "@/store/todos";
// import "bootstrap/dist/css/bootstrap.min.css";


export const metadata = {
  title: 'NKR',
  description: 'Generated by create next app',
}

// thapa technical SUBSCRIBE

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TodosProvider>
          {children}
        </TodosProvider>
      </body>
    </html>
  )
}